import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Terms of Service",
	description: "Terms of Service for WhyDidntIGetTheJob.",
};

export default function TermsPage() {
	return (
		<main className="min-h-[calc(100vh-3.5rem)] px-4 py-12 md:py-16">
			<article className="max-w-3xl mx-auto space-y-8">
				<header className="space-y-2">
					<h1 className="text-3xl md:text-4xl font-bold text-white font-mono">Terms of Service</h1>
					<p className="text-zinc-500 text-sm font-mono">Last updated: March 31, 2026</p>
				</header>

				<section className="space-y-4">
					<h2 className="text-xl font-semibold text-white font-mono">Service Description</h2>
					<p className="text-zinc-400 leading-relaxed">
						WhyDidntIGetTheJob is an AI-powered resume analysis tool. You submit your resume and a
						job description, and our system generates feedback on how well your resume matches the
						role, including a grade, skill gap analysis, and actionable suggestions.
					</p>
				</section>

				<section className="space-y-4">
					<h2 className="text-xl font-semibold text-white font-mono">Free Tier</h2>
					<p className="text-zinc-400 leading-relaxed">
						New users receive 3 free analyses upon signing up. Additional analyses may be available
						for purchase in the future. We reserve the right to change pricing and availability at
						any time.
					</p>
				</section>

				<section className="space-y-4">
					<h2 className="text-xl font-semibold text-white font-mono">Acceptable Use</h2>
					<p className="text-zinc-400 leading-relaxed">You agree not to:</p>
					<ul className="list-disc list-inside text-zinc-400 space-y-2 pl-2">
						<li>Submit content that is illegal, harmful, or violates the rights of others</li>
						<li>
							Use the service to generate content for harassment, discrimination, or any unlawful
							purpose
						</li>
						<li>Attempt to reverse-engineer, exploit, or overload the service</li>
						<li>Submit resumes or job descriptions belonging to others without their consent</li>
						<li>
							Use automated scripts or bots to access the service beyond normal usage patterns
						</li>
					</ul>
				</section>

				<section className="space-y-4">
					<h2 className="text-xl font-semibold text-white font-mono">AI Disclaimer</h2>
					<p className="text-zinc-400 leading-relaxed">
						The analysis provided by WhyDidntIGetTheJob is generated by artificial intelligence and
						is for informational and entertainment purposes only. It is{" "}
						<strong className="text-zinc-300">not professional career advice</strong>. The feedback
						is based on pattern matching between your resume and the job description, and does not
						reflect the actual hiring decisions of any specific company.
					</p>
					<p className="text-zinc-400 leading-relaxed">
						We make no guarantees about the accuracy, completeness, or usefulness of the analysis.
						The &ldquo;hiring manager simulation&rdquo; is a creative interpretation, not a real
						hiring committee review. Use the feedback as one input among many in your job search
						strategy.
					</p>
				</section>

				<section className="space-y-4">
					<h2 className="text-xl font-semibold text-white font-mono">Intellectual Property</h2>
					<p className="text-zinc-400 leading-relaxed">
						You retain ownership of the resume and job description text you submit. The AI-generated
						analysis is provided to you for personal use. You may share your results via the
						shareable URL.
					</p>
				</section>

				<section className="space-y-4">
					<h2 className="text-xl font-semibold text-white font-mono">Limitation of Liability</h2>
					<p className="text-zinc-400 leading-relaxed">
						WhyDidntIGetTheJob is provided &ldquo;as is&rdquo; without warranties of any kind. We
						are not liable for any damages arising from your use of the service, including but not
						limited to career decisions made based on the analysis, data loss, or service
						interruptions.
					</p>
				</section>

				<section className="space-y-4">
					<h2 className="text-xl font-semibold text-white font-mono">Termination</h2>
					<p className="text-zinc-400 leading-relaxed">
						We reserve the right to suspend or terminate your access to the service at any time, for
						any reason, without notice. You may stop using the service at any time.
					</p>
				</section>

				<section className="space-y-4">
					<h2 className="text-xl font-semibold text-white font-mono">Changes to These Terms</h2>
					<p className="text-zinc-400 leading-relaxed">
						We may update these terms from time to time. Continued use of the service after changes
						constitutes acceptance of the updated terms.
					</p>
				</section>

				<section className="space-y-4">
					<h2 className="text-xl font-semibold text-white font-mono">Contact</h2>
					<p className="text-zinc-400 leading-relaxed">
						Questions about these terms? Email{" "}
						<a
							href="mailto:privacy@whydidntigetthejob.com"
							className="text-red-400 hover:underline"
						>
							privacy@whydidntigetthejob.com
						</a>
						.
					</p>
				</section>
			</article>
		</main>
	);
}
