import { NextResponse } from "next/server";
import { jsPDF } from "jspdf";
import { getResult } from "@/lib/storage";

export async function GET(
	request: Request,
	{ params }: { params: Promise<{ id: string }> }
) {
	const { id } = await params;
	const result = await getResult(id);

	if (!result) {
		return NextResponse.json({ error: "Result not found" }, { status: 404 });
	}

	// Create PDF
	const doc = new jsPDF();
	const pageWidth = doc.internal.pageSize.getWidth();
	let y = 20;

	// Helper functions
	const addTitle = (text: string) => {
		doc.setFontSize(20);
		doc.setFont("helvetica", "bold");
		doc.text(text, pageWidth / 2, y, { align: "center" });
		y += 12;
	};

	const addSectionTitle = (text: string) => {
		if (y > 260) {
			doc.addPage();
			y = 20;
		}
		doc.setFontSize(14);
		doc.setFont("helvetica", "bold");
		doc.text(text, 14, y);
		y += 8;
	};

	const addText = (text: string, indent = 14) => {
		doc.setFontSize(10);
		doc.setFont("helvetica", "normal");
		const lines = doc.splitTextToSize(text, pageWidth - indent - 14);
		for (const line of lines) {
			if (y > 280) {
				doc.addPage();
				y = 20;
			}
			doc.text(line, indent, y);
			y += 5;
		}
		y += 3;
	};

	const addBullet = (text: string) => {
		addText(`• ${text}`, 18);
	};

	// Title
	addTitle("Resume Roast Report");
	doc.setFontSize(12);
	doc.setFont("helvetica", "normal");
	doc.text("WhyDidntIGetTheJob.com", pageWidth / 2, y, { align: "center" });
	y += 15;

	// Grade
	doc.setFontSize(48);
	doc.setFont("helvetica", "bold");
	doc.text(result.grade, pageWidth / 2, y + 10, { align: "center" });
	y += 25;

	// Headline
	doc.setFontSize(12);
	doc.setFont("helvetica", "italic");
	const headlineLines = doc.splitTextToSize(`"${result.headline}"`, pageWidth - 40);
	doc.text(headlineLines, pageWidth / 2, y, { align: "center" });
	y += headlineLines.length * 6 + 15;

	// ATS Score
	if (result.atsScore) {
		addSectionTitle(`🤖 ATS Score: ${result.atsScore.score}/100`);
		if (result.atsScore.issues && result.atsScore.issues.length > 0) {
			for (const issue of result.atsScore.issues) {
				addBullet(`[${issue.severity}] ${issue.category}: ${issue.issue}`);
			}
		}
		if (result.atsScore.missingKeywords && result.atsScore.missingKeywords.length > 0) {
			addText(`Missing Keywords: ${result.atsScore.missingKeywords.join(", ")}`);
		}
		y += 5;
	}

	// Competition
	if (result.competition) {
		addSectionTitle("📊 Competition Analysis");
		addText(`Estimated Applicants: ~${result.competition.estimatedApplicants}`);
		addText(`Your Estimated Rank: #${result.competition.estimatedRank}`);
		addText(`Percentile: ${result.competition.percentile}%`);
		addText(`Competition Level: ${result.competition.competitionLevel}`);
		y += 5;
	}

	// Skill Gaps
	if (result.skillGapHeatmap && result.skillGapHeatmap.length > 0) {
		addSectionTitle("🎯 Skill Gap Analysis");
		for (const skill of result.skillGapHeatmap) {
			const status = skill.status === "missing" ? "❌" : skill.status === "weak" ? "⚠️" : "✅";
			addBullet(`${status} ${skill.skill} - ${skill.status.toUpperCase()}`);
		}
		y += 5;
	}

	// Priorities
	if (result.priorities && result.priorities.length > 0) {
		addSectionTitle("🚨 Fix This First");
		for (const priority of result.priorities) {
			addBullet(`#${priority.rank}: ${priority.issue}`);
			addText(`   Action: ${priority.action}`, 22);
			addText(`   Effort: ${priority.effort} | Impact: ${priority.impact}`, 22);
		}
		y += 5;
	}

	// Bullet Rewrite
	if (result.bulletRewrite) {
		addSectionTitle("✨ Free Rewrite");
		addText(`Before: "${result.bulletRewrite.before}"`);
		addText(`After: "${result.bulletRewrite.after}"`);
		addText(`Why: ${result.bulletRewrite.why}`);
		y += 5;
	}

	// The Brutal Truth
	addSectionTitle("🔥 The Brutal Truth");
	addText(result.rejection);
	y += 5;

	// Hiring Manager Quote
	addSectionTitle("💬 What the Hiring Manager Said");
	addText(`"${result.hiringManagerQuote}"`);
	y += 5;

	// Improvements
	if (result.improvements && result.improvements.length > 0) {
		addSectionTitle("💡 How to Actually Get Hired");
		for (let i = 0; i < result.improvements.length; i++) {
			addBullet(`${result.improvements[i]}`);
		}
	}

	// Footer
	doc.addPage();
	y = 20;
	doc.setFontSize(12);
	doc.setFont("helvetica", "normal");
	doc.text("Generated by WhyDidntIGetTheJob.com", pageWidth / 2, y, { align: "center" });
	y += 8;
	doc.setFontSize(10);
	doc.text(`Report ID: ${result.id}`, pageWidth / 2, y, { align: "center" });
	y += 6;
	doc.text(`Generated: ${new Date().toLocaleDateString()}`, pageWidth / 2, y, { align: "center" });

	// Generate PDF buffer
	const pdfBuffer = Buffer.from(doc.output("arraybuffer"));

	return new NextResponse(pdfBuffer, {
		headers: {
			"Content-Type": "application/pdf",
			"Content-Disposition": `attachment; filename="roast-report-${id}.pdf"`,
		},
	});
}
